name: theostos/rocq-test
tag: '9.0'
base_image: theostos/rocq-server:9.0
user: rocq
opam_packages:
opam_env_path: /home/rocq/.opam/4.14.2+flambda
opam_pins: 
- git+https://github.com/theostos/math-comp
